### ISSUE TITLE
Homework 2

### ISSUE THREAD

**Issue by kjacks21** [kjacks21/swe619-fall2018#1]
## Instructions

Goal: Contract Model and Exception Handling.
Reconsider the example in Assignment 1. Modify findPrimeFactor so that it handles all of its preconditions with exceptions. Use the standard exceptions recommended by Bloch. Document this with a revised contract. You can use JavaDoc or you can simply identify the postconditions. 

Grading Criteria:

Adherence to instructions.
Preconditions are correctly converted to exceptions.
Syntax: Java compiles and runs.
You can earn a bonus point for supplying a decent javaDoc specification.

## Tasks

- [x] Update HW1 based on feedback from grader, which means adding in the ability to skip null elements in either list (or at least in the b list) EDIT: done via https://github.com/kjacks21/swe619-fall2018/commit/f8ef275e467ef941be3b07919fb2b781bd8fa736

- [x] Modify findPrimeFactor to handle all preconditions with exceptions, using the ones Bloch recommends

- [x] Revise the contract

- [x] Supply javaDoc specification

**Comment by kjacks21** [comment]
I'll update HW1 based on grader feedback. @1000DS000000, please take a look at what we did when you get a chance. If you'd like to make changes or merge your HW into ours, you are welcome to.

What do you guys think what exceptions we should use? Bloch lists:

1. `IllegalArgumentException` : Non-null parameter value is inappropriate
2. `IllegalStateException` : Object state is inappropriate for method invocation
3. `NullPointerException` : Parameter value is null where prohibited
4. `IndexOutOfBoundsException` : Concurrent modification of an object has been detected where it is prohibited
5. `UnsupportedOperationException` : Object does no support method

**Comment by 1000DS000000** [comment]
We should use the NullPointerException for the first two preconditions. I was also thinking about the IllegalArgumentException for the third one, for when the list that was passed does not have the index of the prime factor.

**Comment by kjacks21** [comment]
I agree with your suggestions. Note that NoSuchElementException is used for iterators and would be inappropriate for the third precondition (this is what I was initially thinking of doing).

How do we want to delegate this? Someone take each task? Or have the tasks be like the following:

1. Implement exception handling for first two preconditions + modify contract for those two preconditions;
2. Implement exception handling for third precondition + modify contract for that precondition; and
3. write a nice javaDoc?

**Comment by ngreenwald89** [comment]
Let's break up the tasking in the second way @kjacks21 proposes. I will take #1., exception handling for first two preconditions.
@1000DS000000 do you know anything about writing a nice JavaDoc? Neither @kjacks21 or I are too familiar, or what particular conventions and examples to follow.

**Comment by ngreenwald89** [comment]
I made a pull request with my code for #1. Feel free to merge into master, modify or make suggestions, or use for #2 and #3.

**Comment by kjacks21** [comment]
I can do task 2. Pushing to your PR

**Comment by kjacks21** [comment]
Done. All that is left are the javaDocs and a review.

**Comment by 1000DS000000** [comment]
I'm not too familiar with javadocs as well, but I'll research on it today and do it.

**Comment by kjacks21** [comment]
Closed as of #2

**Comment by kjacks21** [comment]
@1000DS000000 or @ngreenwald89 can you guys try submitting it? I'm a java noob and just wanted to check that everything is in order, but when I try to compile outside of the project folder associated with this repo I get this business here:

![screen shot 2018-09-11 at 1 35 54 pm](https://user-images.githubusercontent.com/11047068/45377121-a23fa700-b5c7-11e8-9a52-ad5c94f1b9bd.png)

**Comment by kjacks21** [comment]
Issue was the HW2 was made a package. I got it resolved and will submit shortly.
